name: Parkur
favicon: null
layout_spectrum: 0.30449032550677657
typography_spectrum: 0.159364168997854
title: Parkur apie parkur
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.394941525766626
  lightness: 0.5952962613664567
  saturation: 0.20785725768655539
  rhythmicContrast: 0.7934864745475352
purpose: []
